apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stract-data-community-assocations
  namespace: gkgv6
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
