apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stract-data-community-associations
  namespace: ikgrw
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stract-configs-community-associations
  namespace: ikgrw
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
