apiVersion: apps/v1
kind: Deployment
metadata:
  name: stract-backend-6kgrvqaeaaaa
  namespace: ikgrw
  labels:
    app: stract-backend
    hex: 6kgrvqaeaaaa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stract-backend
      hex: 6kgrvqaeaaaa
  template:
    metadata:
      labels:
        app: stract-backend
        hex: 6kgrvqaeaaaa
    spec:  
      containers:
      - name: api
        image: ghcr.io/hexcamp/stract/stract-backend@sha256:d0a227a4e0ff1935b2fd587c98be7c551d6d87fa8b651521036d8879e9ac61e0
        command: [ "/usr/local/bin/stract" ]
        args:
          - api
          - configs/api.toml
        volumeMounts:
           - mountPath: /data
             name: data
           - mountPath: /configs
             name: configs
        ports:
          - protocol: TCP
            containerPort: 3000
            name: api
          - protocol: TCP
            containerPort: 3001
            name: prometheus
          - protocol: TCP
            containerPort: 3005
            name: gossip
          - protocol: TCP
            containerPort: 3011
            name: management
        resources:
          limits:
            memory: 1000Mi
      - name: search-server
        image: ghcr.io/hexcamp/stract/stract-backend@sha256:d0a227a4e0ff1935b2fd587c98be7c551d6d87fa8b651521036d8879e9ac61e0
        command: [ "/usr/local/bin/stract" ]
        args:
          - search-server
          - configs/search_server.toml
        volumeMounts:
           - mountPath: /data
             name: data
           - mountPath: /configs
             name: configs
        ports:
          - protocol: TCP
            containerPort: 3002
            name: search-server
          - protocol: TCP
            containerPort: 3006
            name: gossip
        resources:
          limits:
            memory: 1000Mi
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: stract-data-community-associations
      - name: configs
        persistentVolumeClaim:
          claimName: stract-configs-community-associations
