apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: seahex-wildcard
spec:
  commonName: "*.seahex.org"
  secretName: seahex-wildcard-cert
  dnsNames:
    - "*.seahex.org"
  issuerRef:
    name: letsencrypt-prod-dns
    kind: ClusterIssuer
