apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  annotations:
    projectcontour.io/ingress.class: contour-external
  labels:
    projectcontour.io/ingress.class: contour-external
  name: ipfs-gateway-ipfs-test-hexcamp-wildcard
  namespace: gkgv6
spec:
  routes:
  - conditions:
      - prefix: /
    permitInsecure: false
    services:
    - name: ipfs-gateway-6kgvdnw3nwya
      port: 8080
  virtualhost:
    fqdn: "*.test.hex.camp"
    tls:
      secretName: test-hex-camp-wildcard-cert
---
apiVersion: v1
kind: Secret
metadata:
  name: test-hex-camp-wildcard-cert
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: default/test-hex-camp-wildcard-cert
