apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  annotations:
    projectcontour.io/ingress.class: contour-external
  labels:
    projectcontour.io/ingress.class: contour-external
  name: ipfs-gateway-whimsical-machines-com-bare
  namespace: gkgv6
spec:
  routes:
  - conditions:
      - prefix: /
    permitInsecure: false
    services:
    - name: ipfs-gateway-6kgvdnw3nwya
      port: 8080
  virtualhost:
    fqdn: "whimsicalmachines.com"
    tls:
      secretName: whimsicalmachines.com-cert
---
apiVersion: v1
kind: Secret
metadata:
  name: whimsicalmachines.com-cert
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: default/whimsicalmachines.com-cert
