apiVersion: serving.knative.dev/v1beta1
kind: DomainMapping
metadata:
  name: 6kgrwaaeaaaa.vichex.ca
  namespace: ikgrw
spec:
  ref:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: stract-frontend-community-associations
    namespace: ikgrw
  tls:
    secretName: vichex-wildcard-cert
---
apiVersion: v1
kind: Secret
metadata:
  name: vichex-wildcard-cert
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: default/vichex-wildcard-cert
