apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: stract-frontend-community-associations
  namespace: ikgrw
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/scale-to-zero-pod-retention-period: "30m"
    spec:
      containerConcurrency: 0
      containers:
      - name: frontend
        image: ghcr.io/hexcamp/stract/stract-frontend@sha256:bce14de5a573291557fcaaa27261fcfbc746be64bbbd1407eaf73f6726d20016
        resources: {}
        ports:
          - containerPort: 3000
      enableServiceLinks: false
      timeoutSeconds: 300
