apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  annotations:
    projectcontour.io/ingress.class: contour-external
  labels:
    projectcontour.io/ingress.class: contour-external
  name: repair-event-display
  namespace: repair
spec:
  routes:
  - conditions:
      - prefix: /
    permitInsecure: true
    services:
    - name: event-display
      port: 80
  virtualhost:
    fqdn: repair-event-display.ovh-front-ryzen9.infra.hex.camp
