apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hackmd-updater
  namespace: repair
  labels:
    networking.knative.dev/visibility: cluster-local
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/scale-to-zero-pod-retention-period: "10m"
    spec:
      containerConcurrency: 0
      containers:
      - name: user-container
        envFrom:
        - secretRef:
            name: hackmd-updater
        env:
        - name: IPFS_API
          value: http://ipfs-api-6kgvtnw3nwya.gkgv6.svc.cluster.local:5001/api/v0
        - name: REPO_ORG
          value: hexcamp
        - name: REPO_NAME
          value: hexcamp-coredns-sites
        image: ghcr.io/hexcamp/hackmd-updater@sha256:02b04342e793277e4f279bc083cd4aa276dd07349f8507504ddc7927bdc18568
        volumeMounts:
        resources: {}
      enableServiceLinks: false
      timeoutSeconds: 300
