apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: intertidal
spec:
  commonName: "intertidal.zone"
  secretName: intertidal-zone-cert
  dnsNames:
    - "intertidal.zone"
  issuerRef:
    name: letsencrypt-prod-dns
    kind: ClusterIssuer
