apiVersion: v1
kind: Namespace
metadata:
  name: akpq
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: doh-test-hex-camp-wildcard
  namespace: akpq
spec:
  commonName: "*.doh-test.hex.camp"
  secretName: doh-test-hex-camp-wildcard-cert
  dnsNames:
    - "*.doh-test.hex.camp"
  issuerRef:
    name: letsencrypt-prod-dns
    kind: ClusterIssuer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: coredns-data-akpq
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ubuntu/storage/coredns-data/akpq"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: coredns-data-akpq
  namespace: akpq
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hexcamp-akpq
  namespace: akpq
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/scale-to-zero-pod-retention-period: "30s"
        autoscaling.knative.dev/max-scale: "1"
    spec:
      containerConcurrency: 0
      timeoutSeconds: 120
      containers:
        - image: ghcr.io/hexcamp/hexcamp-coredns-image@sha256:9b9fce0f4e98167ed1b62ccc0db7bc74b1d834edb0c5cc6a05159cbbfbf35602
          command: [ bash, -c ]
          args:
            - |
              set -e
              #while true; do sleep 50; done
              cd /data/h3/20
              while true; do
                /coredns -conf Corefile
                sleep 5
              done
          volumeMounts:
          - name: persistent-storage
            mountPath: /data
          ports:
          - containerPort: 80
          readinessProbe:
            tcpSocket:
              port: 80
          livenessProbe:
            tcpSocket:
              port: 80
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: coredns-data-akpq
          #readOnly: true
---
apiVersion: serving.knative.dev/v1beta1
kind: DomainMapping
metadata:
  name: akpq.doh-test.hex.camp
  namespace: akpq
spec:
  ref:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: hexcamp-akpq
    namespace: akpq
  tls:
    secretName: doh-test-hex-camp-wildcard-cert
