apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: sites-github-clone-listener
spec:
  serviceAccountName: tekton-robot
  triggers:
    - name: sites-github-clone-trigger
      template:
        ref: sites-github-clone-template
  resources:
    kubernetesResource:
      servicePort: 80
