apiVersion: sources.knative.dev/v1alpha1
kind: GitHubSource
metadata:
  name: github-source-sites
  namespace: repair
spec:
  eventTypes:
    - push
  ownerAndRepository: hexcamp/hexcamp-coredns-sites
  accessToken:
    secretKeyRef:
      name: github
      key: ACCESS_TOKEN
  secretToken:
    secretKeyRef:
      name: github
      key: SECRET_TOKEN
  sink:
    ref:
      apiVersion: v1
      kind: Service
      name: el-sites-github-clone-listener
