# https://tekton.dev/docs/how-to-guides/clone-repository/#full-code-samples
# https://hub.tekton.dev/tekton/task/cloudevent
# https://hub.tekton.dev/tekton/task/generate-build-id
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: sites-github-clone
spec:
  description: | 
    This pipeline clones a git repo, then echoes the README file to the stout.
  params:
  - name: repo-url
    type: string
    description: The git repo URL to clone from.
  - name: cloudevent-sink
    type: string
    description: Sink is the uri to send the event to
  workspaces:
  - name: shared-data
    description: | 
      This workspace contains the cloned repo files, so they can be read by the
      next task.
  - name: sites
    description: | 
      PVC for the output sites
#  - name: git-credentials
#    description: My ssh credentials
  tasks:
  - name: get-build-id
    taskRef:
      name: generate-build-id
  - name: fetch-source
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-data
#    - name: ssh-directory
#      workspace: git-credentials
    params:
    - name: url
      value: $(params.repo-url)
    - name: depth
      value: "2"
  - name: show-readme
    runAfter: ["fetch-source"]
    taskRef:
      name: show-readme
    workspaces:
    - name: source
      workspace: shared-data
  - name: show-git-log
    runAfter: ["show-readme"]
    taskRef:
      name: show-git-log
    workspaces:
    - name: source
      workspace: shared-data
  - name: copy-files
    runAfter: ["show-git-log"]
    taskRef:
      name: copy-files
    workspaces:
    - name: source
      workspace: shared-data
    - name: sites
      workspace: sites
  - name: send-cloudevent
    runAfter: ["copy-files"]
    taskRef:
      name: cloudevent
    params:
    - name: sink
      value: $(params.cloudevent-sink)
    - name: eventID
      value: $(tasks.get-build-id.results.build-id)
    - name: eventType
      value: camp.hex.ce.sites-updated
    - name: data
      value: "{}"
