apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: sites-github-clone-template
spec:
  params:
  - name: username
    default: "Kubernetes"
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: sites-github-clone-run-
    spec:
      pipelineRef:
        name: sites-github-clone
      podTemplate:
        securityContext:
          fsGroup: 65532
      workspaces:
      - name: shared-data
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
      - name: sites
        persistentVolumeClaim:
          claimName: sites
      params:
      - name: repo-url
        value: https://github.com/hexcamp/hexcamp-coredns-sites.git
      - name: cloudevent-sink
        value: http://kafka-broker-ingress.knative-eventing.svc.cluster.local/repair/broker
