apiVersion: serving.knative.dev/v1beta1
kind: DomainMapping
metadata:
  name: 6kgvdnw3nw2q.seahex.org
  namespace: gkgv6
spec:
  ref:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: ipfs-service-worker-gateway
    namespace: gkgv6
  tls:
    secretName: seahex-wildcard-cert
