apiVersion: v1
kind: Namespace
metadata:
  name: ai
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: coredns-data-ai
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ubuntu/storage/coredns-data/ai"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: coredns-data-ai
  namespace: ai
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hexcamp-ai
  namespace: ai
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/scale-to-zero-pod-retention-period: "30s"
        autoscaling.knative.dev/max-scale: "1"
    spec:
      containerConcurrency: 0
      timeoutSeconds: 120
      containers:
        #- image: ghcr.io/hexcamp/hexcamp-coredns-image@sha256:9b9fce0f4e98167ed1b62ccc0db7bc74b1d834edb0c5cc6a05159cbbfbf35602
        #  command: [ bash, -c ]
        #  args:
        #    - |
        #      set -e
        #      cd /data/h3/23
        #      while true; do
        #        /coredns -conf Corefile
        #        sleep 5
        #      done
        #      #while true; do sleep 50; done
        - image: coredns/coredns
          workingDir: /data/h3/23
          volumeMounts:
          - name: persistent-storage
            mountPath: /data
          ports:
          - containerPort: 80
          readinessProbe:
            tcpSocket:
              port: 80
          livenessProbe:
            tcpSocket:
              port: 80
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: coredns-data-ai
          #readOnly: true
