apiVersion: v1
kind: ConfigMap
metadata:
  name: feeds
data:
  # file-like keys
  cbc_bc.env: |
    BLUESKY_USERNAME=jim+cbc-bc@jimpick.com
  cbc_bc.feeds: |
    https://www.cbc.ca/webfeed/rss/rss-canada-britishcolumbia
