apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: blueskybot
  namespace: newshub-vanhex
spec:
  serviceAccountName: tekton-robot
  triggers:
    - name: blueskybot
      bindings:
      - ref: blueskybot
      template:
        ref: blueskybot
