apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: blueskybot
  namespace: newshub-vanhex
spec:
  params:
    - name: feed
      type: string
  steps:
    - name: blueskybot
      image: ghcr.io/hexcamp/blueskybot@sha256:973da14864ebec0bb1c1513c98b8894008472fc8cd1c4030a02ebc6d72ef4584
      envFrom:
      - secretRef:
          name: atproto-secrets
      script: |
        #!/bin/sh
        echo "Hello $(params.feed)"
        mkdir -p /workspace/data/$(params.feed)

        cd /workspace/data/$(params.feed)

        cat /feeds/$(params.feed).env > .env
        echo "BLUESKY_PASSWORD=$$(params.feed)_password" >> .env
        echo "SERVICE_URL=https://yvr.whims.io" >> .env
        echo "ALT_TEXT_ENABLED=false" >> .env

        cat /feeds/$(params.feed).feeds > feeds.txt

        # Debug
        #echo ".env:"
        #cat .env
        #echo "feeds.txt:"
        #cat feeds.txt

        # Maintenance: reset json
        #rm -vf /workspace/data/cbc_bc/lastPostedLinks.json
        #exit
        
        #sleep 600
        
        node /app/bot.mjs --once
        echo "Done"
      volumeMounts:
      - name: feeds
        mountPath: "/feeds"
        readOnly: true
  workspaces:
  - name: data
    description: | 
      PVC for the lastPostedLinks.json file
  volumes:
  - name: feeds
    configMap:
      name: feeds
