apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: blueskybot
  namespace: newshub-vanhex
spec:
  params:
    - name: feed
      type: string
  steps:
    - name: blueskybot
      image: ghcr.io/hexcamp/blueskybot@sha256:1e69731e2e2e8c928cfc6ab47eb4e3545e1664d2d130c693b17bcac1e34908ab
      envFrom:
      - secretRef:
          name: atproto-secrets
      script: |
        #!/bin/sh
        echo "Hello $(params.feed)"
        mkdir -p /workspace/data/$(params.feed)
        cd /workspace/data/$(params.feed)
        cat /feeds/$(params.feed).env > .env
        echo "BLUESKY_PASSWORD=$$(params.feed)_password" >> .env
        echo "SERVICE_URL=https://yvr.whims.io" >> .env
        echo "ALT_TEXT_ENABLED=false" >> .env
        #echo ".env:"
        #cat .env
        #cat /feeds/$(params.feed).feeds > feeds.txt
        #echo "feeds.txt:"
        #cat feeds.txt
        #
        rm -vf /workspace/data/cbc_bc/lastPostedLinks.json
        exit
        #sleep 600
        node /app/bot.mjs --once
        echo "Done"
      volumeMounts:
      - name: feeds
        mountPath: "/feeds"
        readOnly: true
  workspaces:
  - name: data
    description: | 
      PVC for the lastPostedLinks.json file
  volumes:
  - name: feeds
    configMap:
      name: feeds
