apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: blueskybot
  namespace: newshub-vanhex
spec:
  params:
    - name: feed
      type: string
  steps:
    - name: blueskybot
      image: ghcr.io/hexcamp/blueskybot@sha256:91a27b8acf35a0146e23a3f54d7b4a6550b636bea7879f5e5330d9f914165827
      script: |
        #!/bin/sh
        echo "Hello $(params.feed)"
        sleep 600
        echo "Done"
  workspaces:
  - name: data
    description: | 
      PVC for the lastPostedLinks.json file
