apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: blueskybot
  namespace: newshub-vanhex
spec:
  params:
  - name: feed
    default: "Unknown"
  resourcetemplates:
  - apiVersion: tekton.dev/v1
    kind: TaskRun
    metadata:
      generateName: blueskybot-
    spec:
      taskRef:
        name: blueskybot
      params:
      - name: feed
        value: $(tt.params.feed)
      workspaces:
      - name: data
        persistentVolumeClaim:
          claimName: data-blueskybot
