apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ip-collector
  namespace: repair
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/scale-to-zero-pod-retention-period: "15m"
    spec:
      containerConcurrency: 0
      containers:
      - name: user-container
        env:
        - name: PATH
          value: "/root/.local/bin:/cnb/process:/cnb/lifecycle:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/data/hexcamp-coredns"
        envFrom:
        - secretRef:
            name: aws-credentials
        image: ghcr.io/hexcamp/hexcamp-knative-images/zone-generator-image@sha256:33bf1796b76f06d7846824ec04d0e9f1ef9e6f3d08e350b552e70c2d27e7d859
        volumeMounts:
        - mountPath: "/data"
          name: data-vol
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: 0
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: 0
          successThreshold: 1
        resources: {}
      volumes:
      - name: data-vol
        persistentVolumeClaim:
          claimName: ips
      enableServiceLinks: false
      timeoutSeconds: 300
