apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ip-collector
  namespace: repair
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/scale-to-zero-pod-retention-period: "1m"
        networking.knative.dev/visibility: cluster-local
    spec:
      containerConcurrency: 0
      containers:
      - name: user-container
        command: [ "/cnb/process/function" ]
        image: ghcr.io/hexcamp/hexcamp-knative-images/generic-cloudevent-service-image@sha256:87c923e3a0f93e178be65e60937b0e64bc1d3a5303c633ee3bbfa00566c18024 
        volumeMounts:
        - mountPath: "/ips"
          name: ips-vol
        - mountPath: "/scripts"
          name: scripts-vol
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: 0
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: 0
          successThreshold: 1
        resources: {}
      volumes:
      - name: ips-vol
        persistentVolumeClaim:
          claimName: ips
      - name: scripts-vol
        configMap:
          name: scripts
      enableServiceLinks: false
      timeoutSeconds: 300
