# https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ksvc.yaml
  - pvc.yaml
  - trigger.yaml
configMapGenerator:
  - name: foo-data
    files:
      - foo.json
generatorOptions:
  disableNameSuffixHash: true
