# https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ksvc.yaml
  - pvc.yaml
  - trigger.yaml
  - sink-binding.yaml
configMapGenerator:
  - name: scripts
    files:
      - process-cloudevent.sh
generatorOptions:
  disableNameSuffixHash: true
