apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  annotations:
    projectcontour.io/ingress.class: contour-external
  labels:
    projectcontour.io/ingress.class: contour-external
  name: ipfs-cluster-api-seahex
  namespace: gkgv6
spec:
  routes:
  - conditions:
      - prefix: /
    permitInsecure: true
    services:
    - name: ipfs-cluster-api
      port: 9094
  virtualhost:
    fqdn: "6kgvhnw3nwya.seahex.org"
    tls:
      secretName: seahex-wildcard-cert
