apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: zone-generator
  namespace: repair
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/scale-to-zero-pod-retention-period: "30m"
    spec:
      containerConcurrency: 0
      containers:
      - name: user-container
        env:
        - name: PATH
          value: "/root/.nvm/versions/node/v24.12.0/bin:/root/.local/bin:/cnb/process:/cnb/lifecycle:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/data/hexcamp-coredns"
        envFrom:
        - secretRef:
            name: aws-credentials
        image: ghcr.io/hexcamp/hexcamp-knative-images/zone-generator-image@sha256:e15b1d767707777ccd3f415423aee29b156c3cf0525493dd90bf98eae811fc72
        command: [ "/cnb/process/function" ]
        volumeMounts:
        - mountPath: "/data"
          name: data-vol
        - mountPath: "/sites"
          name: sites-vol
        - mountPath: "/ips"
          name: ips-vol
        resources: {}
      volumes:
      - name: data-vol
        persistentVolumeClaim:
          claimName: repair-hexcamp-coredns
      - name: sites-vol
        persistentVolumeClaim:
          claimName: sites
      - name: ips-vol
        persistentVolumeClaim:
          claimName: ips
      enableServiceLinks: false
      timeoutSeconds: 300
