apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: zone-generator
  namespace: repair
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/scale-to-zero-pod-retention-period: "15m"
    spec:
      containerConcurrency: 0
      containers:
      - name: user-container
        env:
        - name: PATH
          value: "/cnb/process:/cnb/lifecycle:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/data/hexcamp-coredns"
        envFrom:
        - secretRef:
            name: aws-credentials
        image: ghcr.io/hexcamp/hexcamp-knative-images/zone-generator-image@sha256:e1bd02ff3097afdf3ed034386ab6dc7ca6a8d2e505306f484b1b83138ae63dde
        volumeMounts:
        - mountPath: "/data"
          name: data-vol
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: 0
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: 0
          successThreshold: 1
        resources: {}
      volumes:
      - name: data-vol
        persistentVolumeClaim:
          claimName: repair-hexcamp-coredns
      enableServiceLinks: false
      timeoutSeconds: 300
