apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: zone-generator
  namespace: repair
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/scale-to-zero-pod-retention-period: "30m"
    spec:
      containerConcurrency: 0
      containers:
      - name: user-container
        env:
        - name: PATH
          value: "/root/.local/bin:/cnb/process:/cnb/lifecycle:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/data/hexcamp-coredns"
        envFrom:
        - secretRef:
            name: aws-credentials
        image: ghcr.io/hexcamp/hexcamp-knative-images/zone-generator-image@sha256:64298309e3502d4aa7921bc5b9e98f457d063b822fa731add3015e7340bc0954
        command: [ "/cnb/process/function" ]
        volumeMounts:
        - mountPath: "/data"
          name: data-vol
        - mountPath: "/sites"
          name: sites-vol
        - mountPath: "/ips"
          name: ips-vol
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: 0
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: 0
          successThreshold: 1
        resources: {}
      volumes:
      - name: data-vol
        persistentVolumeClaim:
          claimName: repair-hexcamp-coredns
      - name: sites-vol
        persistentVolumeClaim:
          claimName: sites
      - name: ips-vol
        persistentVolumeClaim:
          claimName: ips
      enableServiceLinks: false
      timeoutSeconds: 300
