apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: zone-generator
  namespace: repair
spec:
  broker: broker
  filter: {}
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: zone-generator
      namespace: repair
