# This Trigger subscribes to the Broker and will forward all the events that it received to zone-generator.
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: zone-generator
  namespace: repair
spec:
  broker: broker
  filters:
    - any:
      - exact:
          type: camp.hex.ce.ips-updated
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: zone-generator
  delivery:
    timeout: "300s"
