apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hexcamp-coredns-demo-doh2
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/scale-to-zero-pod-retention-period: "15m"
    spec:
      containerConcurrency: 0
      timeoutSeconds: 120
      containers:
        - image: coredns/coredns:1.11.1
          command: [ bash, -c ]
          args:
            - |
              set -e
              while true; do sleep 50; done
