apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hexcamp-dnsfun
  namespace: quick
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/scale-to-zero-pod-retention-period: "15m"
    spec:
      containerConcurrency: 0
      timeoutSeconds: 120
      containers:
        - image: ghcr.io/hexcamp/hexcamp-dns:latest@sha256:ec5b50cf759f8b87945508c0d6eb3f79cbca76a0795f97e1c1e0c4c9e7102a00
