apiVersion: serving.knative.dev/v1beta1
kind: DomainMapping
metadata:
  name: test-doh2.infra.hex.camp
  namespace: default
spec:
  ref:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: hexcamp-coredns-demo-doh2
    namespace: default
  tls:
    secretName: hex-camp-infra-wildcard-cert
