# https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/examples/kubernetes/static_provisioning/README.md
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: coredns-test-efs-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
