apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: coredns-test-efs-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: efs-sc-hexcamp-coredns
  resources:
    requests:
      storage: 5Gi
