apiVersion: v1
kind: Namespace
metadata:
  name: as7q
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-as7q
provisioner: efs.csi.aws.com
reclaimPolicy: Retain
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: doh-test-hex-camp-wildcard
  namespace: as7q
spec:
  commonName: "*.doh-test.hex.camp"
  secretName: doh-test-hex-camp-wildcard-cert
  dnsNames:
    - "*.doh-test.hex.camp"
  issuerRef:
    name: letsencrypt-prod-dns
    kind: ClusterIssuer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: coredns-test-efs-claim
  namespace: as7q
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: efs-as7q
  resources:
    requests:
      storage: 5Gi
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hexcamp-as7q
  namespace: as7q
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/scale-to-zero-pod-retention-period: "15m"
    spec:
      containerConcurrency: 0
      timeoutSeconds: 120
      containers:
        - image: ghcr.io/hexcamp/hexcamp-coredns-image@sha256:9b9fce0f4e98167ed1b62ccc0db7bc74b1d834edb0c5cc6a05159cbbfbf35602
          command: [ bash, -c ]
          args:
            - |
              set -e
              #while true; do sleep 50; done
              cd /data/coredns-data/as7q/h3/37
              while true; do
                /coredns -conf Corefile
                sleep 5
              done
          volumeMounts:
          - name: persistent-storage
            mountPath: /data
          ports:
          - containerPort: 80
          readinessProbe:
            tcpSocket:
              port: 80
          livenessProbe:
            tcpSocket:
              port: 80
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: coredns-test-efs-claim
          #readOnly: true
---
apiVersion: serving.knative.dev/v1beta1
kind: DomainMapping
metadata:
  name: as7q.doh-test.hex.camp
  namespace: as7q
spec:
  ref:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: hexcamp-as7q
    namespace: as7q
  tls:
    secretName: doh-test-hex-camp-wildcard-cert
