apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: infra-hex-camp-wildcard
  namespace: default
spec:
  commonName: "*.infra.hex.camp"
  secretName: infra-hex-camp-wildcard-cert
  dnsNames:
    - "*.infra.hex.camp"
  issuerRef:
    name: letsencrypt-prod-dns
    kind: ClusterIssuer
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ""
