apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: intertidal
spec:
  commonName: "intertidal.zone"
  secretName: intertidal-zone-cert
  dnsNames:
    - "intertidal.zone"
  issuerRef:
    name: letsencrypt-prod-dns
    kind: ClusterIssuer
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ""
