apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: whimsicalmachines.com
spec:
  commonName: "whimsicalmachines.com"
  secretName: whimsicalmachines.com-cert
  dnsNames:
    - "whimsicalmachines.com"
  issuerRef:
    name: letsencrypt-prod-dns
    kind: ClusterIssuer
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ""
