apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vanhex-bare
spec:
  commonName: "vanhex.ca"
  secretName: vanhex-bare-cert
  dnsNames:
    - "vanhex.ca"
  issuerRef:
    name: letsencrypt-prod-dns
    kind: ClusterIssuer
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ""
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vanhex-wildcard
spec:
  commonName: "*.vanhex.ca"
  secretName: vanhex-wildcard-cert
  dnsNames:
    - "*.vanhex.ca"
  issuerRef:
    name: letsencrypt-prod-dns
    kind: ClusterIssuer
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ""
