apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: whimsicalmachines.com
spec:
  commonName: "whimsicalmachines.com"
  secretName: whimsicalmachines.com-cert
  dnsNames:
    - "whimsicalmachines.com"
  issuerRef:
    name: letsencrypt-prod-dns
    kind: ClusterIssuer
