---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hex-camp-bare
spec:
  commonName: "hex.camp"
  secretName: hex-camp-bare-cert
  dnsNames:
    - "hex.camp"
  issuerRef:
    name: letsencrypt-prod-dns
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hex-camp-wildcard
spec:
  commonName: "*.hex.camp"
  secretName: hex-camp-wildcard-cert
  dnsNames:
    - "*.hex.camp"
  issuerRef:
    name: letsencrypt-prod-dns
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-hex-camp-wildcard
spec:
  commonName: "*.test.hex.camp"
  secretName: test-hex-camp-wildcard-cert
  dnsNames:
    - "*.test.hex.camp"
  issuerRef:
    name: letsencrypt-prod-dns
    kind: ClusterIssuer
