apiVersion: batch/v1
kind: CronJob
metadata:
  name: tofu
  namespace: repair
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: tofu
            image: ghcr.io/hexcamp/hexcamp-knative-images/tofu-spot-watcher@sha256:46d91a92e87e857746e358dc98cd9a0c17f3805eb4491e73601740c9833ca948
            envFrom:
            - secretRef:
                name: aws-credentials
            command: [ sh, -c ]
            args:
            - |
              set -euxo pipefail
              cd /data
              #while true; do sleep 60; done
              if [ ! -d hexcamp-terraform-aws-minikube ]; then
                git clone https://github.com/hexcamp/hexcamp-terraform-aws-minikube.git
              fi
              cd hexcamp-terraform-aws-minikube
              git pull
              echo ">>> minikube7"
              cd examples/minikube7
              ./update-cronjob.sh
              cd ../..
              echo ">>> minikube8"
              cd examples/minikube8
              ./update-cronjob.sh
              cd ../..
              echo ">>> minikube9"
              cd examples/minikube9
              ./update-cronjob.sh && update-ns1-test-hex-camp-cronjob.sh
              cd ../..
              echo ">>> minikube10"
              cd examples/minikube10
              ./update-cronjob.sh && update-ns2-test-hex-camp-cronjob.sh
              cd ../..
            volumeMounts:
            - mountPath: "/data"
              name: data-vol
          volumes:
          - name: data-vol
            persistentVolumeClaim:
              claimName: repair-hexcamp-terraform-aws-minikube
          restartPolicy: Never
