apiVersion: batch/v1
kind: Job
metadata:
  name: tofu
  namespace: repair
spec:
  template:
    spec:
      containers:
      - name: tofu
        image: ghcr.io/hexcamp/hexcamp-knative-images/tofu-spot-watcher@sha256:46d91a92e87e857746e358dc98cd9a0c17f3805eb4491e73601740c9833ca948
        envFrom:
        - secretRef:
            name: aws-credentials
        command: [ sh, -c ]
        args:
        - |
          set -euxo pipefail
          cd /data
          if [ ! -d hexcamp-terraform-aws-minikube ]; then
            git clone https://github.com/hexcamp/hexcamp-terraform-aws-minikube.git
          fi
          cd hexcamp-terraform-aws-minikube
          git pull
          while true; do sleep 50; done
        volumeMounts:
        - mountPath: "/data"
          name: data-vol
        readinessProbe: null
      restartPolicy: Never
      volumes:
      - name: data-vol
        persistentVolumeClaim:
          claimName: repair-hexcamp-terraform-aws-minikube
  backoffLimit: 4
