apiVersion: batch/v1
kind: Job
metadata:
  name: tofu
  namespace: repair
spec:
  template:
    spec:
      containers:
      - name: tofu
        image: docker pull ghcr.io/hexcamp/hexcamp-knative-images/tofu-spot-watcher@sha256:46d91a92e87e857746e358dc98cd9a0c17f3805eb4491e73601740c9833ca948
        envFrom:
        - secretRef:
            name: aws-credentials
        command: "sh"
        args:
        - |
          while true; do sleep 50; done
        volumeMounts:
        - mountPath: "/data"
          name: data-vol
      restartPolicy: Never
      volumes:
      - name: data-vol
        persistentVolumeClaim:
          claimName: repair-hexcamp-coredns
  backoffLimit: 4
