apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: repair-hexcamp-terraform-aws-minikube
  namespace: repair
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
